### ISSUE TITLE
Support for darwin-arm64 in further releases

### ISSUE THREAD

**Issue by joan-s-molas** [invidian/terraform-provider-gpg#10]
It would be nice to have support for darwin-amd64 in forthcoming releases - so the provider can run on newer macOS versions on Apple M1 silicon.

Please kindly consider adding support for that OS/architecture combination.

**Comment by invidian** [comment]
Thanks for opening the issue. Last release has been made using Goreleaser, so as long Goreleaser supports it, it should be easy.

Perhaps https://github.com/invidian/terraform-provider-gpg/blob/master/.goreleaser.yml needs to be updated somehow.

**Comment by joan-s-molas** [comment]
I think that in order to support darwin-arm64 the go version needs to be at least 1.16:

https://github.com/goreleaser/goreleaser/issues/1952
