### ISSUE TITLE
Unable to download invidian/gpg v0.3.1 from terraform 1.6

### ISSUE THREAD

**Issue by rvrajendra** [invidian/terraform-provider-gpg#16]
Unable to download provider plugin
Error while installing invidian/gpg v.0.3.1: error checking signature:
openpgp: key expired

Seems not downloading with terraform 1.6.0. It's able to download with a lower version say 1.4

**Comment by invidian** [comment]
Thanks for reporting. It looks like this issue affects many providers and it's not trivial to resolve: https://github.com/hashicorp/terraform/issues/33984.

**Comment by invidian** [comment]
This is resolved with Terraform version v1.6.1 as far as I understand. Closing.
